### ISSUE TITLE
Can't figure out how to pass gRPC metadata?

### ISSUE THREAD

**Issue by mkhludnev** [yandex-cloud/yandex-cloud-ml-sdk#25]
I'm aiming https://yandex.cloud/ru/docs/foundation-models/operations/disable-logging for sure, but can't find how to do it with `YCloudML`. 
Is should be something around interceptors?

**Comment by vhaldemar** [comment]
Hey!
It shoud be interceptor, yes.
But you could wait for a ~~week and release of `0.2.0`, I will add this feature in shortwhile.

Link for a memo:
https://github.com/langchain-ai/langchain/blob/b509747c7f13c5cad2226e62a3c9d948664fa193/libs/community/langchain_community/llms/yandex.py#L111

**Comment by mkhludnev** [comment]
Well..  Were wondering who's that commit https://github.com/langchain-ai/langchain/commit/a017f49fd3423f525beaf9f8df8f23af279c1a74 Thanks for reminder.
Meanwhile I made an grpc interceptor passed into YCloudML let me know if it's worth to spin off PR.

**Comment by vhaldemar** [comment]
> Well.. Were wondering who's that commit https://github.com/langchain-ai/langchain/commit/a017f49fd3423f525beaf9f8df8f23af279c1a74 Thanks for reminder.

Oh wow :)

> Meanwhile I made an grpc interceptor passed into YCloudML let me know if it's worth to spin off PR.

As an interceptor - I'm not sure if it is a good idea to grow number of inteceptors.
I planned to to it as explicit branch in a `_client.py` contolled by SDK's init-flag.

**Comment by vhaldemar** [comment]
Will be in a next release, stay tuned
